pipeline {
    agent any

    // This securely loads your AWS credentials from Jenkins so Terraform can use them
    environment {
        AWS_ACCESS_KEY_ID     = credentials('aws-access-key')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-key')
    }

    stages {
        stage('Checkout Code') {
            steps {
                git credentialsId: 'Githubpass', url: 'https://github.com/Sandesh2080/Boardgame/Terraform.git', branch: 'main'
            }
        }

        stage('Terraform Init') {
            steps {
                sh 'terraform init'
            }
        }

        stage('Terraform Plan') {
            steps {
                // Creates a plan file so we know exactly what will be applied
                sh 'terraform plan -out=tfplan'
            }
        }

        stage('Terraform Apply') {
            steps {
                // The -auto-approve equivalent is necessary in CI/CD so it doesn't wait for human typing
                sh 'terraform apply -input=false tfplan'
            }
        }
    }
}
